spring.application.name=supplog

# PostgreSQL Ba?lant? Bilgileri
spring.datasource.url=jdbc:postgresql://localhost:5432/supplog_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true


# JPA / Hibernate Ayarlar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true