spring.application.name=supplog

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/supplog_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}