CREATE TABLE public.role (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30),
    CONSTRAINT role_name_check CHECK (
        name IN ('ROLE_USER', 'ROLE_ADMIN')
    ),
    CONSTRAINT role_pkey PRIMARY KEY (id)
);


CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    birth_date date,
    created_at timestamp(6) without time zone,
    e_mail varchar(254),
    first_name varchar(50),
    is_deleted boolean,
    last_name varchar(50),
    password varchar(255),
    score integer,
    updated_at timestamp(6) without time zone,
    user_name varchar(30),
    token_version integer DEFAULT 0 NOT NULL,
    time_zone varchar(64) NOT NULL,

    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT ukehv2osdo3bfokh566calsfx32 UNIQUE (e_mail),
    CONSTRAINT ukk8d0f2n7n88w1a16yhua64onx UNIQUE (user_name)
);


CREATE TABLE public.users_roles (
    user_id bigint NOT NULL,
    role_id integer NOT NULL,

    CONSTRAINT users_roles_pkey
        PRIMARY KEY (user_id, role_id),

    CONSTRAINT uk_user_roles_user_role
        UNIQUE (user_id, role_id),

    CONSTRAINT fk_users_roles_user
        FOREIGN KEY (user_id)
        REFERENCES public.users(id),

    CONSTRAINT fk_users_roles_role
        FOREIGN KEY (role_id)
        REFERENCES public.role(id)
);


CREATE TABLE public.supplements (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NOT NULL,
    expire_date date NOT NULL,
    is_deleted boolean NOT NULL,
    supplement_name varchar(100) NOT NULL,
    supplement_dosage varchar(100) NOT NULL,
    category varchar(30) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    inserted_by_user_id bigint NOT NULL,

    CONSTRAINT supplements_pkey
        PRIMARY KEY (id),

    CONSTRAINT supplements_category_check CHECK (
        category IN ('MEDICINE', 'SUPPLEMENT', 'VITAMIN')
    ),

    CONSTRAINT fk_supplements_user
        FOREIGN KEY (inserted_by_user_id)
        REFERENCES public.users(id)
);


CREATE TABLE public.routines (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    day_of_month integer,
    duration_type varchar(20) NOT NULL,
    end_date date,
    frequency varchar(30) NOT NULL,
    is_deleted boolean NOT NULL,
    routine_time time(0) without time zone,
    start_date date NOT NULL,
    supplement_id bigint NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,

    CONSTRAINT routines_pkey
        PRIMARY KEY (id),

    CONSTRAINT routines_duration_type_check CHECK (
        duration_type IN ('UNTIL_DATE', 'LIFE_TIME')
    ),

    CONSTRAINT routines_frequency_check CHECK (
        frequency IN (
            'DAILY',
            'WEEKLY',
            'MONTHLY',
            'SPECIFIC_DAYS',
            'AS_NEEDED'
        )
    ),

    CONSTRAINT fk_routines_supplement
        FOREIGN KEY (supplement_id)
        REFERENCES public.supplements(id),

    CONSTRAINT fk_routines_user
        FOREIGN KEY (user_id)
        REFERENCES public.users(id)
);


CREATE TABLE public.routine_days (
    routine_id bigint NOT NULL,
    day_name varchar(20) NOT NULL,

    CONSTRAINT pk_routine_days
        PRIMARY KEY (routine_id, day_name),

    CONSTRAINT routine_days_day_name_check CHECK (
        day_name IN (
            'MONDAY',
            'TUESDAY',
            'WEDNESDAY',
            'THURSDAY',
            'FRIDAY',
            'SATURDAY',
            'SUNDAY'
        )
    ),

    CONSTRAINT fk_routine_days_routine
        FOREIGN KEY (routine_id)
        REFERENCES public.routines(id)
);


CREATE TABLE public.routine_executions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NOT NULL,
    resolved_at timestamp(6) with time zone,
    scheduled_at timestamp(6) with time zone NOT NULL,
    scheduled_date date NOT NULL,
    scheduled_time time(0) without time zone NOT NULL,
    scheduled_zone_id varchar(64) NOT NULL,
    status varchar(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    routine_id bigint NOT NULL,

    CONSTRAINT routine_executions_pkey
        PRIMARY KEY (id),

    CONSTRAINT routine_executions_status_check CHECK (
        status IN (
            'PENDING',
            'COMPLETED',
            'SKIPPED',
            'MISSED'
        )
    ),

    CONSTRAINT uk_routine_execution_routine_date
        UNIQUE (routine_id, scheduled_date),

    CONSTRAINT fk_routine_execution_routine
        FOREIGN KEY (routine_id)
        REFERENCES public.routines(id)
);


CREATE TABLE public.support_relationships (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    access_scope varchar(30) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    requested_at timestamp(6) without time zone NOT NULL,
    responded_at timestamp(6) without time zone,
    revoked_at timestamp(6) without time zone,
    status varchar(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    supported_user_id bigint NOT NULL,
    supporter_user_id bigint NOT NULL,

    CONSTRAINT support_relationships_pkey
        PRIMARY KEY (id),

    CONSTRAINT support_relationships_access_scope_check CHECK (
        access_scope IN (
            'ALL_ROUTINES',
            'SELECTED_ROUTINES'
        )
    ),

    CONSTRAINT support_relationships_status_check CHECK (
        status IN (
            'PENDING',
            'ACCEPTED',
            'REJECTED',
            'CANCELLED',
            'REVOKED'
        )
    ),

    CONSTRAINT uk_support_relationship_users
        UNIQUE (supported_user_id, supporter_user_id),

    CONSTRAINT fk_support_relationship_supported_user
        FOREIGN KEY (supported_user_id)
        REFERENCES public.users(id),

    CONSTRAINT fk_support_relationship_supporter
        FOREIGN KEY (supporter_user_id)
        REFERENCES public.users(id)
);


CREATE TABLE public.support_routine_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NOT NULL,
    routine_id bigint NOT NULL,
    support_relationship_id bigint NOT NULL,

    CONSTRAINT support_routine_permissions_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_support_permission_relationship_routine
        UNIQUE (support_relationship_id, routine_id),

    CONSTRAINT fk_support_permission_routine
        FOREIGN KEY (routine_id)
        REFERENCES public.routines(id),

    CONSTRAINT fk_support_permission_relationship
        FOREIGN KEY (support_relationship_id)
        REFERENCES public.support_relationships(id)
);