ALTER TABLE public.users
    ADD COLUMN must_change_password boolean DEFAULT false NOT NULL;

CREATE TABLE public.admin_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id bigint NOT NULL,
    action varchar(80) NOT NULL,
    resource_type varchar(40) NOT NULL,
    resource_id bigint,
    old_value text,
    new_value text,
    reason varchar(500) NOT NULL,
    successful boolean NOT NULL,
    error_message varchar(500),
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT fk_admin_audit_admin_user
        FOREIGN KEY (admin_user_id) REFERENCES public.users(id)
);

CREATE INDEX idx_admin_audit_created_at
    ON public.admin_audit_logs(created_at DESC);

CREATE INDEX idx_admin_audit_resource
    ON public.admin_audit_logs(resource_type, resource_id);
